name = "genq-api"
main = "src/index.js"
compatibility_date = "2024-09-23"

account_id = "462809e24d9075765b54cd1fd0842591"

# KV Namespace for storing quiz data
[[kv_namespaces]]
  binding = "GENQ_KV"
  id = "b48af9d4f7ff44c09ba106b97709fc73"

# Environment variables
[vars]
GEMINI_API_KEY = ""
